### ISSUE TITLE
Not able to copy files over 4 GB

### ISSUE THREAD

**Issue by SpikeSP87** [liuervehc/nxmtp#4]
Hi,

It doesn't let copy files over 4 GB; when it reaches 4 GB, it stops (no error log, no error message, but sounds an alert of error). Then in NX-Shell (per example),  can be seen the file was transferred only until 4 GB exactly, not more nor less.
MicroSD formatted as exFAT, so not FAT32 related problem. Files under 4 GB, no problem.
Windows 10 x64, but i don't think it's an OS related problem.

**Comment by liuervehc** [comment]
This is an intended behavior of this software.

**Comment by pmferraro** [comment]
same problem

**Comment by ghost** [comment]
Why is this expected behavior? I'd think if it was formatted as exfat, it shouldn't make a difference

**Comment by leo60228** [comment]
@pmferraro @z0oinks MTP doesn't support files greater than 4GB.

**Comment by SpikeSP87** [comment]
@leo60228 that's not true. You can transfer files bigger than 4 GB through MTP protocol. Usually, the most common scenario is using a FAT32 filesystem on devices using external sd card storage (like tablets or smartphones), so this is a normal limitation (due to filesystem, not to the MTP protocol), but there are other filesystems (as exFAT, F2FS....) where that limitation (4 GB max filesize) related to filesystem doesn't exist. In fact, I have transferred right now a file about 6,36 GB to my smartphone through MTP... 

Anyways, there are ways to implement MTP Protocol without the 32 bit limitation and being able to transfer files bigger than 4 GB (as Android OS MTP implementation does, per example).
Some clues about that fact: https://medium.com/@bandan/media-transfer-protocol-and-4gb-file-transfers-effe74663a63
